from __future__ import annotations

DEFECT_FIELDS = [
    ("外観キズ", "txtKizu"),
    ("圧痕", "txtAkkon"),
    ("切粉", "txtKiriko"),
    ("毟れ", "txtMusire"),
    ("穴大", "txtAnadai"),
    ("穴小", "txtAnashou"),
    ("穴キズ", "txtAnakizu"),
    ("バリ", "txtBari"),
    ("短寸", "txtTansun"),
    ("面粗", "txtMenso"),
    ("サビ", "txtSabi"),
    ("ボケ", "txtBoke"),
    ("挽目", "txtHikime"),
    ("汚れ", "txtYogore"),
    ("メッキ", "txtMekki"),
    ("落下", "txtRakka"),
    ("フクレ", "txtHukure"),
    ("ツブレ", "txtTubure"),
    ("ボッチ", "txtBotti"),
    ("段差", "txtDansa"),
    ("バレル石", "txtBareru"),
    ("径プラス", "txtKeiPlus"),
    ("径マイナス", "txtKeiMinus"),
    ("ゲージ", "txtGeiji"),
    ("異物混入", "txtIbutu"),
    ("形状不良", "txtKeijou"),
    ("こすれ", "txtKosure"),
    ("変色シミ", "txtHenshoku"),
    ("材料キズ", "txtZairyo"),
    ("ゴミ", "txtGomi"),
    ("その他", "txtSonota"),
]
