CREATE SCHEMA IF NOT EXISTS public;
SET search_path TO public;

CREATE TABLE IF NOT EXISTS defect_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    production_lot_id varchar(7),
    part_number varchar(30),
    instruction_date date,
    machine_no varchar(5),
    inspector_1 varchar(6),
    inspector_2 varchar(6),
    inspector_3 varchar(6),
    inspector_4 varchar(6),
    inspector_5 varchar(20),
    work_minutes integer,
    quantity integer,
    total_defect_count integer,
    defect_rate double precision,
    appearance_scratch integer,
    dent integer,
    chip integer,
    tear integer,
    hole_large integer,
    hole_small integer,
    hole_scratch integer,
    burr integer,
    short_length integer,
    rough_surface integer,
    rust integer,
    blur integer,
    turning_mark integer,
    stain integer,
    plating integer,
    drop_damage integer,
    blister integer,
    crush integer,
    projection integer,
    step integer,
    barrel_stone integer,
    diameter_plus integer,
    diameter_minus integer,
    gauge integer,
    foreign_matter integer,
    shape_defect integer,
    rub_mark integer,
    discoloration integer,
    material_scratch integer,
    dust integer,
    other integer,
    other_detail varchar(10)
);

CREATE TABLE IF NOT EXISTS inspection_records (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    recorded_at timestamp,
    production_lot_id varchar(7),
    inspector_id varchar(4),
    process_name varchar(30),
    machine_no varchar(5)
);

CREATE TABLE IF NOT EXISTS inspector_master (
    inspector_id varchar(4),
    inspector_name varchar(5),
    category varchar(5),
    visible boolean NOT NULL DEFAULT true
);

CREATE TABLE IF NOT EXISTS product_catalog (
    production_lot_id varchar(7),
    machine_no varchar(5),
    part_number varchar(30),
    part_name varchar(30),
    customer_name varchar(30),
    instruction_date date,
    quantity integer
);

CREATE TABLE IF NOT EXISTS product_master (
    product_number varchar(30),
    product_name varchar(30),
    customer_name varchar(30),
    person_in_charge varchar(6),
    material varchar(255),
    has_instruction_sheet varchar(1),
    washing_1 varchar(10),
    process_2 varchar(30),
    process_3 varchar(30),
    process_4 varchar(30),
    process_5 varchar(30),
    process_6 varchar(30),
    process_7 varchar(30),
    process_8 varchar(30),
    process_9 varchar(30),
    packing_type varchar(30),
    packing_spec varchar(30),
    shipping_destination varchar(30),
    product_id varchar(6),
    process_2_note varchar(20),
    process_3_note varchar(20),
    process_4_note varchar(20),
    process_5_note varchar(20),
    process_6_note varchar(20),
    process_7_note varchar(20),
    process_8_note varchar(20),
    process_9_note varchar(20),
    unit_price double precision,
    material_type integer,
    handling_note varchar(20),
    next_process varchar(10),
    call_code varchar(8),
    unit_weight double precision,
    process_2_summary varchar(2),
    process_3_summary varchar(2),
    process_4_summary varchar(2),
    process_5_summary varchar(2),
    process_6_summary varchar(2),
    process_7_summary varchar(2),
    process_8_summary varchar(2)
);

CREATE TABLE IF NOT EXISTS qr_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY,
    recorded_at timestamp,
    qr_code varchar(22),
    production_lot_id varchar(7),
    event_at timestamp,
    process varchar(2),
    position varchar(2),
    quantity integer,
    process_code varchar(2),
    process_name varchar(30),
    updated_flag varchar(1)
);
